FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/app .
COPY .env .env

EXPOSE 6060

CMD ["./app"]

#docker buildx create --use --name draftlybuilder-crud || docker buildx use draftlybuilder-crud
#docker buildx build --no-cache --platform linux/amd64,linux/arm64 -t rich329/draftly-crud:v0.0.1 --push .



#docker pull rich329/draftly-crud:v0.0.1
# or can just run this directly
#docker run -d -p 6060:6060 --name draftly-crud rich329/draftly-crud:v0.0.1


# IP:3.13.161.172